### ISSUE TITLE
Migrate to Nuxt 2

### ISSUE THREAD

**Issue by jedisct1** [DNSCrypt/dnscrypt-website#1]
https://medium.com/nuxt/nuxt-2-is-coming-oh-yeah-212c1a9e1a67

**Comment by jedisct1** [comment]
I gave it a quick spin but faced an incompatibility with markdown-it:

```
 ERROR  TypeError: Cannot set property 'md' of undefined
    at Builder.extendBuild.config (/Users/j/src/dnscrypt-website/node_modules/@nuxtjs/markdownit/index.js:21:39)
    at Builder.<anonymous> (/Users/j/src/dnscrypt-website/node_modules/nuxt-edge/dist/nuxt.js:199:23)
    at WebpackServerConfig.config (/Users/j/src/dnscrypt-website/node_modules/nuxt-edge/dist/nuxt.js:11038:56)
    at Builder.webpackBuild (/Users/j/src/dnscrypt-website/node_modules/nuxt-edge/dist/nuxt.js:11460:52)
    at Builder.build (/Users/j/src/dnscrypt-website/node_modules/nuxt-edge/dist/nuxt.js:11174:16)
    at <anonymous>
```

Any idea?

**Comment by denji** [comment]
`plugins: ['~/plugins/md-it']`

**Comment by publicarray** [comment]
Nuxt 2 has some awesome changes.

> Any idea?

Sorry none besides reporting the issue to markdown-it or waiting a bit until issues like this are sorted out upstream.

**Comment by Mei152** [comment]
I encountered the exact same issue.  I am using markdown-it for netlify cms.

**Comment by Mei152** [comment]
I was going to try markedjs, but got sidetracked on another front trying to make photoswipe work.  So, no, I have no solution yet.

**Comment by Mei152** [comment]
@jedisct1 
Looks like this is related https://github.com/nuxt-community/modules/pull/203
